In [9]:
#imports
import pandas as pd
import numpy as np
import os
raw_file = pd.read_csv("D:/Data_CHU/predict_ttf1.csv")
raw_file

,id,Lame manquante,Type histologique,ttf1,Age,Sexe,Pièce op,TNM,Tabac,Atcd carcinologiqsues
0,25P13027,NaN,Adénocarcinome G3,+,77.0,F,PO,T1a N0,oui,cancer du sein
1,25P16493,NaN,Carcinoide typique,-,64.0,H,PO,T1c N0,Non,Non
2,25P16544,NaN,Pas de cancer,-,85.0,F,PO,NaN,NaN,NaN
3,25P17513,NaN,Adénocarcinome G2,+,52.0,H,PO,T1c N0,Oui,Non
4,25P18147,NaN,Adénocarcinome G3,+,80.0,F,PO,T3N0,Oui,"Vessie, Sein"
...,...,...,...,...,...,...,...,...,...,...
108,26P4222,NaN,NaN,+,NaN,NaN,NaN,NaN,NaN,NaN
109,26P4381,NaN,NaN,+,NaN,NaN,NaN,NaN,NaN,NaN
110,26P4575,NaN,NaN,+,NaN,NaN,NaN,NaN,NaN,NaN
111,26P4751,NaN,NaN,+,NaN,NaN,NaN,NaN,NaN,NaN
112,26P7178,NaN,NaN,-,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
working_df = raw_file[['id','ttf1']]
working_df = working_df.drop_duplicates()
working_df['label'] =

In [ ]:
working_df["label"] = working_df["ttf1"].str.contains(r"\+").astype(int)

           id ttf1  label
0    25P13027    +      1
1    25P16493    -      0
2    25P16544   -       0
3    25P17513    +      1
4    25P18147    +      1
..        ...  ...    ...
108   26P4222    +      1
109   26P4381    +      1
110   26P4575    +      1
111   26P4751    +      1
112   26P7178    -      0

[111 rows x 3 columns]

In [14]:
working_df = working_df[['id','label']]
working_df.to_csv('C:/Users/manon/Documents/pathology_MIL/data/splits_chu/data_chu.csv', index=False)

In [1]:
"""
Script de répartition des fichiers .h5 en dossiers train / validation / test
basé sur le fichier data_chu_split.csv

Version sécurisée pour fichiers HDF5 :
- copie au lieu de déplacement
- vérification taille fichier
- vérification ouverture HDF5
- gestion des erreurs
"""

import pandas as pd
import shutil
import argparse
from pathlib import Path
import os
import h5py


def verify_h5_file(path: Path) -> bool:
    """
    Vérifie qu'un fichier HDF5 peut être ouvert correctement.
    """
    try:
        with h5py.File(path, "r"):
            return True
    except Exception as e:
        print(f"  [CORRUPTED] {path.name} : {e}")
        return False


def split_files(csv_path: str, h5_dir: str, output_dir: str) -> None:
    df = pd.read_csv(csv_path)

    h5_dir = Path(h5_dir)
    output_dir = Path(output_dir)

    # Créer les sous-dossiers
    for folder in ["train", "validation", "test"]:
        (output_dir / folder).mkdir(parents=True, exist_ok=True)

    stats = {
        "train": 0,
        "validation": 0,
        "test": 0,
        "skipped": 0,
        "failed": 0,
    }

    for _, row in df.iterrows():
        file_id = row["slide_id"]
        split = row["set"]

        src = h5_dir / f"{file_id}.h5"

        if not src.exists():
            print(f"  [SKIP] {src.name} introuvable")
            stats["skipped"] += 1
            continue

        # Vérification source avant copie
        if not verify_h5_file(src):
            print(f"  [SKIP] {src.name} source corrompue")
            stats["failed"] += 1

            continue

        dst = output_dir / split / src.name

        try:
            # Copie avec métadonnées
            shutil.copy2(src, dst)

            # Vérification taille
            src_size = os.path.getsize(src)
            dst_size = os.path.getsize(dst)

            if src_size != dst_size:
                print(f"  [FAILED] {src.name} taille différente après copie")
                dst.unlink(missing_ok=True)
                stats["failed"] += 1
                continue

            # Vérification ouverture HDF5 destination
            if not verify_h5_file(dst):
                print(f"  [FAILED] {src.name} copie corrompue")
                dst.unlink(missing_ok=True)
                stats["failed"] += 1
                continue

            print(f"  [OK]   {src.name} → {split}/")
            stats[split] += 1

        except Exception as e:
            print(f"  [ERROR] {src.name} : {e}")
            stats["failed"] += 1

    # Résumé
    print("\n── Résumé ──────────────────────────────")
    print(f"  train      : {stats['train']} fichier(s)")
    print(f"  validation        : {stats['validation']} fichier(s)")
    print(f"  test       : {stats['test']} fichier(s)")
    print(f"  skippés    : {stats['skipped']} fichier(s)")
    print(f"  erreurs    : {stats['failed']} fichier(s)")
    print("────────────────────────────────────────")


csv_dir = "C:/Users/manon/Documents/pathology_MIL/data/splits_chu/data_chu_split.csv"

h5_dir_target = "C:/Users/manon/Documents/pathology_MIL/data/CHU_UNI2_embeds/IHC/"
h5_dir = "D:/Embeddings/Data_CHU/UNI2H_embeddings/IHC"

split_files(csv_dir, h5_dir, h5_dir_target)

  [OK]   25P13027.h5 → train/
  [OK]   25P16493.h5 → train/
  [OK]   25P16544.h5 → train/
  [OK]   25P17513.h5 → test/
  [OK]   25P18147.h5 → test/
  [OK]   25P7216.h5 → test/
  [OK]   25P9801.h5 → train/
  [OK]   25P9947.h5 → train/
  [OK]   25P11397.h5 → train/
  [OK]   25P11414.h5 → validation/
  [OK]   25P12995.h5 → train/
  [OK]   25P6168.h5 → train/
  [OK]   25P6193_1.h5 → train/
  [OK]   25P6193.h5 → train/
  [OK]   25P7615.h5 → train/
  [OK]   25P7883.h5 → train/
  [OK]   25P8416.h5 → train/
  [OK]   25P8589.h5 → train/
  [OK]   25P9546.h5 → test/
  [OK]   25P9546.h5 → train/
  [OK]   25P9599.h5 → train/
  [CORRUPTED] 25P15592.h5 : Unable to synchronously open file (bad object header version number)
  [SKIP] 25P15592.h5 source corrompue
  [OK]   25P16135.h5 → train/
  [OK]   25P16569.h5 → train/
  [OK]   25P18069.h5 → train/
  [OK]   25P18616.h5 → test/
  [OK]   25P18860.h5 → validation/
  [OK]   25P19032.h5 → test/
  [OK]   25P19078.h5 → train/
  [OK]   25P19219.h5 → train/
  [OK]   25P19249.h5 → validation/
  [OK]   25P20177.h5 → train/
  [OK]   25P20417.h5 → validation/
  [OK]   25P20512.h5 → train/
  [OK]   25P21646.h5 → train/
  [OK]   25P24425.h5 → train/
  [OK]   25P24484.h5 → train/
  [OK]   25P25119.h5 → train/
  [OK]   25P25378.h5 → train/
  [OK]   25P25453.h5 → validation/
  [OK]   25P25508.h5 → train/
  [OK]   25P25891.h5 → train/
  [OK]   25P26238.h5 → train/
  [OK]   25P26312.h5 → train/
  [OK]   25P26677.h5 → train/
  [OK]   25P27185.h5 → validation/
  [OK]   25P27185.h5 → train/
  [OK]   25P29704.h5 → train/
  [OK]   25P29744.h5 → test/
  [OK]   25P29928.h5 → train/
  [OK]   25P30045.h5 → train/
  [OK]   25P30107.h5 → train/
  [OK]   25P30572.h5 → train/
  [OK]   25P30606.h5 → train/
  [OK]   25P34206.h5 → test/
  [OK]   25P34745.h5 → train/
  [OK]   25P35649.h5 → validation/
  [OK]   25P36271.h5 → train/
  [SKIP] 26P45463.h5 introuvable
  [SKIP] 26P450.h5 introuvable
  [OK]   26P17.h5 → test/
  [OK]   25P45703.h5 → train/
  [OK]   26P394.h5 → train/
  [OK]   25P45537.h5 → train/
  [OK]   26P315.h5 → test/
  [SKIP] 26P699.h5 introuvable
  [OK]   25P45423.h5 → validation/
  [OK]   25P45358.h5 → train/
  [OK]   25P43260.h5 → test/
  [OK]   25P41007.h5 → train/
  [OK]   25P41007.h5 → train/
  [OK]   25P40892.h5 → test/
  [SKIP] 26P55.h5 introuvable
  [OK]   26P174.h5 → validation/
  [OK]   26P174.h5 → train/
  [OK]   26p231.h5 → test/
  [SKIP] 26P767.h5 introuvable
  [SKIP] 26P906.h5 introuvable
  [OK]   26P1106.h5 → validation/
  [OK]   26P1166.h5 → train/
  [OK]   26P1168.h5 → train/
  [OK]   26P1274.h5 → train/
  [OK]   26P1287.h5 → train/
  [SKIP] 26P1641.h5 introuvable
  [OK]   26P1755.h5 → train/
  [OK]   26P1758.h5 → train/
  [OK]   26P1948.h5 → train/
  [OK]   26P2121.h5 → train/
  [OK]   26P2188.h5 → test/
  [OK]   26P2218.h5 → train/
  [OK]   26P2243.h5 → train/
  [OK]   26P2752.h5 → train/
  [OK]   26P2949.h5 → validation/
  [OK]   26p3048.h5 → validation/
  [OK]   26p3048.h5 → train/
  [OK]   26P3134.h5 → train/
  [OK]   26P3166.h5 → train/
  [OK]   26P3172.h5 → train/
  [OK]   26P3209.h5 → test/
  [OK]   26P3226.h5 → train/
  [OK]   26P3268.h5 → train/
  [OK]   26P3270.h5 → train/
  [OK]   26P3890.h5 → train/
  [SKIP] 26P3979.h5 introuvable
  [SKIP] 26P4180.h5 introuvable
  [SKIP] 26P4222.h5 introuvable
  [SKIP] 26P4381.h5 introuvable
  [SKIP] 26P4575.h5 introuvable
  [SKIP] 26P4751.h5 introuvable
  [SKIP] 26P7178.h5 introuvable

── Résumé ──────────────────────────────
  train      : 68 fichier(s)
  validation        : 12 fichier(s)
  test       : 15 fichier(s)
  skippés    : 14 fichier(s)
  erreurs    : 1 fichier(s)
────────────────────────────────────────